import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import pg from 'pg';
import {readFile} from 'node:fs/promises';
import {randomBytes,scrypt as scryptCb,createHash,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';

const app=Fastify({logger:true});
const db=new pg.Pool({connectionString:process.env.DATABASE_URL});
const scrypt=promisify(scryptCb);
const COOKIE='baqala_session';
await app.register(cookie);
await app.register(helmet,{contentSecurityPolicy:false});
await app.register(rateLimit,{max:180,timeWindow:'1 minute'});

async function hashPassword(password){const salt=randomBytes(16).toString('hex');const d=await scrypt(password,salt,64);return `scrypt$${salt}$${Buffer.from(d).toString('hex')}`}
async function verifyPassword(password,value){const[,salt,hex]=String(value||'').split('$');if(!salt||!hex)return false;const e=Buffer.from(hex,'hex');const a=Buffer.from(await scrypt(password,salt,e.length));return e.length===a.length&&timingSafeEqual(e,a)}
const h=t=>createHash('sha256').update(t).digest('hex');

async function init(){
 await db.query(`
 CREATE TABLE IF NOT EXISTS live_users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,email text UNIQUE NOT NULL,password text NOT NULL,role text NOT NULL DEFAULT 'customer',city text,created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS live_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES live_users(id) ON DELETE CASCADE,token_hash text UNIQUE NOT NULL,expires_at timestamptz NOT NULL);
 CREATE TABLE IF NOT EXISTS live_providers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid UNIQUE REFERENCES live_users(id) ON DELETE CASCADE,title text NOT NULL,bio text,city text NOT NULL,district text,verified boolean DEFAULT false,rating numeric(3,2) DEFAULT 0,rating_count int DEFAULT 0,completed int DEFAULT 0,lat numeric(9,6),lng numeric(9,6));
 CREATE TABLE IF NOT EXISTS live_services(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),provider_id uuid REFERENCES live_providers(id),category text NOT NULL,title text NOT NULL,description text NOT NULL,price numeric(18,2),pricing text DEFAULT 'STARTING_FROM',location_type text DEFAULT 'CUSTOMER_LOCATION',duration int DEFAULT 60,status text DEFAULT 'ACTIVE',created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS live_bookings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),customer_id uuid REFERENCES live_users(id),provider_id uuid REFERENCES live_providers(id),service_id uuid REFERENCES live_services(id),status text DEFAULT 'PENDING',starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,description text NOT NULL,location text,price numeric(18,2),created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS live_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),booking_id uuid UNIQUE REFERENCES live_bookings(id),customer_id uuid REFERENCES live_users(id),provider_id uuid REFERENCES live_providers(id),rating int CHECK(rating BETWEEN 1 AND 5),comment text,created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS live_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),booking_id uuid REFERENCES live_bookings(id),sender_id uuid REFERENCES live_users(id),body text NOT NULL,created_at timestamptz DEFAULT now());
 CREATE INDEX IF NOT EXISTS live_service_filter ON live_services(category,status,created_at);
 CREATE INDEX IF NOT EXISTS live_booking_provider ON live_bookings(provider_id,status,starts_at,ends_at);
 `);
 if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){const email=process.env.ADMIN_EMAIL.toLowerCase();const q=await db.query('SELECT id FROM live_users WHERE email=$1',[email]);if(!q.rows[0])await db.query('INSERT INTO live_users(name,email,password,role) VALUES($1,$2,$3,$4)',['مدير بقالة',email,await hashPassword(process.env.ADMIN_PASSWORD),'admin'])}
}
async function current(req){const token=req.cookies[COOKIE];if(!token)return null;const q=await db.query(`SELECT u.*,(SELECT id FROM live_providers p WHERE p.user_id=u.id) provider_id FROM live_sessions s JOIN live_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()`,[h(token)]);return q.rows[0]||null}
async function need(req,res,roles=[]){const u=await current(req);if(!u){res.code(401).send({error:'AUTH_REQUIRED'});return null}if(roles.length&&!roles.includes(u.role)){res.code(403).send({error:'FORBIDDEN'});return null}return u}
async function issueSession(res,userId){const token=randomBytes(32).toString('base64url');await db.query("INSERT INTO live_sessions(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '30 days')",[userId,h(token)]);res.setCookie(COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/'});}

app.get('/api/health',async()=>({status:'ok',service:'baqala-live',version:'1.0.0'}));
app.get('/api/categories',async()=>[['home','صيانة المنازل','⌂'],['electrical','الكهرباء','⚡'],['design','التصميم والإبداع','✦'],['tech','الخدمات التقنية','⌘'],['education','التعليم والدروس','⌁'],['business','خدمات الأعمال','▥'],['cars','خدمات السيارات','◉'],['events','خدمات المناسبات','◇'],['cleaning','التنظيف','✧'],['photo','التصوير والمونتاج','◍']].map(([slug,name,icon])=>({slug,name,icon})));
app.post('/api/auth/register',async(req,res)=>{const b=req.body||{};if(!b.name||!b.email||String(b.password||'').length<10)return res.code(400).send({error:'INVALID_INPUT'});try{const q=await db.query('INSERT INTO live_users(name,email,password,city) VALUES($1,$2,$3,$4) RETURNING id,name,email,role,city',[b.name,String(b.email).toLowerCase(),await hashPassword(b.password),b.city||null]);await issueSession(res,q.rows[0].id);return q.rows[0]}catch{return res.code(409).send({error:'ACCOUNT_EXISTS'})}});
app.post('/api/auth/login',async(req,res)=>{const b=req.body||{};const q=await db.query('SELECT * FROM live_users WHERE email=$1',[String(b.email||'').toLowerCase()]);const u=q.rows[0];if(!u||!await verifyPassword(b.password||'',u.password))return res.code(401).send({error:'INVALID_CREDENTIALS'});await issueSession(res,u.id);return{id:u.id,name:u.name,email:u.email,role:u.role}});
app.post('/api/auth/logout',async(req,res)=>{const t=req.cookies[COOKIE];if(t)await db.query('DELETE FROM live_sessions WHERE token_hash=$1',[h(t)]);res.clearCookie(COOKIE,{path:'/'});return{ok:true}});
app.get('/api/auth/me',async(req,res)=>{const u=await need(req,res);if(u)return{id:u.id,name:u.name,email:u.email,role:u.role,providerId:u.provider_id}});

app.get('/api/services',async(req)=>{const q=req.query||{},v=[],w=["s.status='ACTIVE'"];if(q.q){v.push(`%${q.q}%`);w.push(`s.title ILIKE $${v.length}`)}if(q.category){v.push(q.category);w.push(`s.category=$${v.length}`)}if(q.city){v.push(q.city);w.push(`p.city=$${v.length}`)}const x=await db.query(`SELECT s.*,p.title provider_title,p.city,p.district,p.verified,p.rating,p.rating_count,u.name provider_name FROM live_services s JOIN live_providers p ON p.id=s.provider_id JOIN live_users u ON u.id=p.user_id WHERE ${w.join(' AND ')} ORDER BY s.created_at DESC LIMIT 50`,v);return x.rows});
app.get('/api/services/:id',async(req,res)=>{const q=await db.query(`SELECT s.*,p.id provider_id,p.title provider_title,p.bio provider_bio,p.city,p.district,p.verified,p.rating,p.rating_count,p.completed,u.name provider_name FROM live_services s JOIN live_providers p ON p.id=s.provider_id JOIN live_users u ON u.id=p.user_id WHERE s.id=$1`,[req.params.id]);if(!q.rows[0])return res.code(404).send({error:'NOT_FOUND'});return q.rows[0]});
app.post('/api/provider/onboard',async(req,res)=>{const u=await need(req,res);if(!u)return;const b=req.body||{};try{const q=await db.query('INSERT INTO live_providers(user_id,title,bio,city,district,lat,lng) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[u.id,b.title,b.bio||null,b.city,b.district||null,b.lat||null,b.lng||null]);await db.query("UPDATE live_users SET role='provider' WHERE id=$1",[u.id]);return q.rows[0]}catch{return res.code(409).send({error:'PROVIDER_EXISTS'})}});
app.post('/api/services',async(req,res)=>{const u=await need(req,res,['provider','admin']);if(!u)return;const p=(await db.query('SELECT id FROM live_providers WHERE user_id=$1',[u.id])).rows[0];if(!p)return res.code(400).send({error:'PROVIDER_REQUIRED'});const b=req.body||{};const q=await db.query('INSERT INTO live_services(provider_id,category,title,description,price,pricing,location_type,duration) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[p.id,b.category,b.title,b.description,b.price||null,b.pricing||'STARTING_FROM',b.locationType||'CUSTOMER_LOCATION',b.duration||60]);return q.rows[0]});

app.get('/api/bookings',async(req,res)=>{const u=await need(req,res);if(!u)return;const q=await db.query(`SELECT b.*,s.title service_title,pu.name provider_name,cu.name customer_name FROM live_bookings b JOIN live_services s ON s.id=b.service_id JOIN live_providers p ON p.id=b.provider_id JOIN live_users pu ON pu.id=p.user_id JOIN live_users cu ON cu.id=b.customer_id WHERE b.customer_id=$1 OR p.user_id=$1 ORDER BY b.created_at DESC`,[u.id]);return q.rows});
app.post('/api/bookings',async(req,res)=>{const u=await need(req,res);if(!u)return;const b=req.body||{};const s=(await db.query('SELECT s.*,p.user_id FROM live_services s JOIN live_providers p ON p.id=s.provider_id WHERE s.id=$1 AND s.status=$2',[b.serviceId,'ACTIVE'])).rows[0];if(!s)return res.code(404).send({error:'SERVICE_NOT_FOUND'});if(s.user_id===u.id)return res.code(400).send({error:'OWN_SERVICE'});const start=new Date(b.startsAt),end=new Date(start.getTime()+(s.duration||60)*60000);const c=await db.query(`SELECT 1 FROM live_bookings WHERE provider_id=$1 AND status IN ('ACCEPTED','CONFIRMED','IN_PROGRESS') AND starts_at<$3 AND ends_at>$2 LIMIT 1`,[s.provider_id,start,end]);if(c.rows[0])return res.code(409).send({error:'SLOT_UNAVAILABLE'});const q=await db.query('INSERT INTO live_bookings(customer_id,provider_id,service_id,starts_at,ends_at,description,location,price) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[u.id,s.provider_id,s.id,start,end,b.description,b.location||null,s.price]);return q.rows[0]});
const flow={PENDING:['ACCEPTED','REJECTED','CANCELLED'],ACCEPTED:['CONFIRMED','CANCELLED'],CONFIRMED:['IN_PROGRESS','CANCELLED'],IN_PROGRESS:['COMPLETED'],COMPLETED:[],CANCELLED:[],REJECTED:[]};
app.patch('/api/bookings/:id/status',async(req,res)=>{const u=await need(req,res);if(!u)return;const b=(await db.query('SELECT b.*,p.user_id provider_user FROM live_bookings b JOIN live_providers p ON p.id=b.provider_id WHERE b.id=$1',[req.params.id])).rows[0];if(!b)return res.code(404).send({error:'NOT_FOUND'});const to=req.body?.status;if(!flow[b.status]?.includes(to))return res.code(400).send({error:'INVALID_TRANSITION'});if(['ACCEPTED','REJECTED','CONFIRMED','IN_PROGRESS','COMPLETED'].includes(to)&&u.id!==b.provider_user&&u.role!=='admin')return res.code(403).send({error:'PROVIDER_ACTION_REQUIRED'});if(['ACCEPTED','CONFIRMED'].includes(to)){const c=await db.query(`SELECT 1 FROM live_bookings WHERE id<>$1 AND provider_id=$2 AND status IN ('ACCEPTED','CONFIRMED','IN_PROGRESS') AND starts_at<$4 AND ends_at>$3 LIMIT 1`,[b.id,b.provider_id,b.starts_at,b.ends_at]);if(c.rows[0])return res.code(409).send({error:'SLOT_UNAVAILABLE'})}await db.query('UPDATE live_bookings SET status=$1 WHERE id=$2',[to,b.id]);if(to==='COMPLETED')await db.query('UPDATE live_providers SET completed=completed+1 WHERE id=$1',[b.provider_id]);return{ok:true,status:to}});
app.post('/api/reviews',async(req,res)=>{const u=await need(req,res);if(!u)return;const b=(await db.query('SELECT * FROM live_bookings WHERE id=$1',[req.body?.bookingId])).rows[0];if(!b||b.customer_id!==u.id||b.status!=='COMPLETED')return res.code(403).send({error:'REVIEW_REQUIRES_COMPLETED_BOOKING'});try{await db.query('INSERT INTO live_reviews(booking_id,customer_id,provider_id,rating,comment) VALUES($1,$2,$3,$4,$5)',[b.id,u.id,b.provider_id,req.body.rating,req.body.comment||null]);const a=(await db.query('SELECT avg(rating) rating,count(*) count FROM live_reviews WHERE provider_id=$1',[b.provider_id])).rows[0];await db.query('UPDATE live_providers SET rating=$1,rating_count=$2 WHERE id=$3',[a.rating,a.count,b.provider_id]);return{ok:true}}catch{return res.code(409).send({error:'ALREADY_REVIEWED'})}});
app.get('/api/admin/stats',async(req,res)=>{const u=await need(req,res,['admin']);if(!u)return;const count=async t=>+(await db.query(`SELECT count(*) c FROM ${t}`)).rows[0].c;return{users:await count('live_users'),providers:await count('live_providers'),services:await count('live_services'),bookings:await count('live_bookings'),completed:+(await db.query("SELECT count(*) c FROM live_bookings WHERE status='COMPLETED'")).rows[0].c}});

const html=await readFile(new URL('./app.html',import.meta.url),'utf8');
app.get('/*',async(_req,res)=>res.type('text/html').send(html));
await init();
await app.listen({port:Number(process.env.PORT||3000),host:'0.0.0.0'});
